#!/bin/sh

usage(){
	echo "usage: git ffcheck [master | develop]"
}

main(){
	if [ $1 != "master" -a $1 != "develop" ]; then
		usage
		exit 1
	fi

	CURRENT_REV=`git rev-list HEAD | head -1`
	TARGET_REV=`git rev-list $1 | head -1`
	git rev-list ${CURRENT_REV}..${TARGET_REV}
}

main "$@"